name: Generate Report CSV

permissions:
    contents: write

on:
  push:
    branches:
      - main

jobs:
  Create_CSV:
    runs-on: ubuntu-latest
    steps:
    -   name: checkout
        uses: actions/checkout@v4

    -   name: execute py script # run file
        run: |
          python cflare.py
    -   name: Upload to repo
        uses: actions/upload-artifact@v4
        with:
            name: resultado_headers
            path: ${{github.workspace}}/resultado_headers.csv
 #   -   name: download artifact to data
 #       uses: actions/download-artifact@v4
 #       with:
 #           name: distribution
 #           path: ${{github.workspace}}/data
    -   uses: stefanzweifel/git-auto-commit-action@v6
        with:
            commit_message: commit report to repo
